//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinLab.Code.PresentationLayer.GUISistema {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecursosUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosUI() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinLab.Code.PresentationLayer.GUISistema.RecursosUI", typeof(RecursosUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        public static string BtnUI1 {
            get {
                return ResourceManager.GetString("BtnUI1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General.
        /// </summary>
        public static string BtnUIConfig1 {
            get {
                return ResourceManager.GetString("BtnUIConfig1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sonido.
        /// </summary>
        public static string BtnUIConfig2 {
            get {
                return ResourceManager.GetString("BtnUIConfig2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accesibilidad.
        /// </summary>
        public static string BtnUIConfig3 {
            get {
                return ResourceManager.GetString("BtnUIConfig3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Predetermin..
        /// </summary>
        public static string BtnUIConfig4 {
            get {
                return ResourceManager.GetString("BtnUIConfig4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string BtnUIConfig5 {
            get {
                return ResourceManager.GetString("BtnUIConfig5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar.
        /// </summary>
        public static string BtnUIConfig6 {
            get {
                return ResourceManager.GetString("BtnUIConfig6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string LblUI1 {
            get {
                return ResourceManager.GetString("LblUI1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string LblUI2 {
            get {
                return ResourceManager.GetString("LblUI2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Discapacidad Visual.
        /// </summary>
        public static string LblUIAccesibilidad1 {
            get {
                return ResourceManager.GetString("LblUIAccesibilidad1", resourceCulture);
            }
        }
    }
}
