//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinLab.Code.DataLayer.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProcAdd {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProcAdd() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinLab.Code.DataLayer.Recursos.ProcAdd", typeof(ProcAdd).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a add_cuenta.
        /// </summary>
        internal static string add_cuenta {
            get {
                return ResourceManager.GetString("add_cuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a add_examen.
        /// </summary>
        internal static string add_examen {
            get {
                return ResourceManager.GetString("add_examen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a add_grupo.
        /// </summary>
        internal static string add_grupo {
            get {
                return ResourceManager.GetString("add_grupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a add_grupo_item.
        /// </summary>
        internal static string add_grupo_item {
            get {
                return ResourceManager.GetString("add_grupo_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a add_item.
        /// </summary>
        internal static string add_item {
            get {
                return ResourceManager.GetString("add_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a add_listaItem.
        /// </summary>
        internal static string add_listaItem {
            get {
                return ResourceManager.GetString("add_listaItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a add_orden.
        /// </summary>
        internal static string add_orden {
            get {
                return ResourceManager.GetString("add_orden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a add_paciente.
        /// </summary>
        internal static string add_paciente {
            get {
                return ResourceManager.GetString("add_paciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a add_plantilla.
        /// </summary>
        internal static string add_plantilla {
            get {
                return ResourceManager.GetString("add_plantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a add_plantilla_item.
        /// </summary>
        internal static string add_plantilla_item {
            get {
                return ResourceManager.GetString("add_plantilla_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a add_seguridad.
        /// </summary>
        internal static string add_seguridad {
            get {
                return ResourceManager.GetString("add_seguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a add_tipocampo.
        /// </summary>
        internal static string add_tipocampo {
            get {
                return ResourceManager.GetString("add_tipocampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a add_tipoitem.
        /// </summary>
        internal static string add_tipoitem {
            get {
                return ResourceManager.GetString("add_tipoitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a insert_ordenDetalle.
        /// </summary>
        internal static string insert_ordenDetalle {
            get {
                return ResourceManager.GetString("insert_ordenDetalle", resourceCulture);
            }
        }
    }
}
