//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinLab.Code.DataLayer.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProcDel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProcDel() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinLab.Code.DataLayer.Recursos.ProcDel", typeof(ProcDel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DEL_MEDICO.
        /// </summary>
        internal static string DEL_MEDICO {
            get {
                return ResourceManager.GetString("DEL_MEDICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DEL_ORDENCAB.
        /// </summary>
        internal static string DEL_ORDENCAB {
            get {
                return ResourceManager.GetString("DEL_ORDENCAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DEL_ORDENDET.
        /// </summary>
        internal static string DEL_ORDENDET {
            get {
                return ResourceManager.GetString("DEL_ORDENDET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DEL_PACIENTE.
        /// </summary>
        internal static string DEL_PACIENTE {
            get {
                return ResourceManager.GetString("DEL_PACIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DEL_TARIFARIOCAB.
        /// </summary>
        internal static string DEL_TARIFARIOCAB {
            get {
                return ResourceManager.GetString("DEL_TARIFARIOCAB", resourceCulture);
            }
        }
    }
}
