//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinLab.Code.DataLayer.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProcGet {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProcGet() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinLab.Code.DataLayer.Recursos.ProcGet", typeof(ProcGet).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a existen_examen.
        /// </summary>
        internal static string existen_examen {
            get {
                return ResourceManager.GetString("existen_examen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_all_plantilla.
        /// </summary>
        internal static string get_all_plantilla {
            get {
                return ResourceManager.GetString("get_all_plantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_all_tipocampo.
        /// </summary>
        internal static string get_all_tipocampo {
            get {
                return ResourceManager.GetString("get_all_tipocampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_all_tipoItem.
        /// </summary>
        internal static string get_all_tipoItem {
            get {
                return ResourceManager.GetString("get_all_tipoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_allItemsByPlantilla.
        /// </summary>
        internal static string get_allItemsByPlantilla {
            get {
                return ResourceManager.GetString("get_allItemsByPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_allOrdenByPacienteByFecha.
        /// </summary>
        internal static string get_allOrdenByFecha {
            get {
                return ResourceManager.GetString("get_allOrdenByFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_allOrdenByFechaByEstado.
        /// </summary>
        internal static string get_allOrdenByFechaByEstado {
            get {
                return ResourceManager.GetString("get_allOrdenByFechaByEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_allOrdenByPacienteByFechaByEstado.
        /// </summary>
        internal static string get_allOrdenByPacienteByFechaByEstado {
            get {
                return ResourceManager.GetString("get_allOrdenByPacienteByFechaByEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_codPlantillaByPaquete.
        /// </summary>
        internal static string get_codPlantillaByPaquete {
            get {
                return ResourceManager.GetString("get_codPlantillaByPaquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_cuenta.
        /// </summary>
        internal static string get_cuenta {
            get {
                return ResourceManager.GetString("get_cuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_examenByOrdenDetalle.
        /// </summary>
        internal static string get_examenByOrdenDetalle {
            get {
                return ResourceManager.GetString("get_examenByOrdenDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_examenDetalleByExamen.
        /// </summary>
        internal static string get_examenDetalleByExamen {
            get {
                return ResourceManager.GetString("get_examenDetalleByExamen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_exist.
        /// </summary>
        internal static string get_exist {
            get {
                return ResourceManager.GetString("get_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_grupoByPlantilla.
        /// </summary>
        internal static string get_grupoByPlantilla {
            get {
                return ResourceManager.GetString("get_grupoByPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_itemByGrupo.
        /// </summary>
        internal static string get_itemByGrupo {
            get {
                return ResourceManager.GetString("get_itemByGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_itemByPlantilla.
        /// </summary>
        internal static string get_itemByPlantilla {
            get {
                return ResourceManager.GetString("get_itemByPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_listaByItem.
        /// </summary>
        internal static string get_listaByItem {
            get {
                return ResourceManager.GetString("get_listaByItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_ordenByAreaByYearByMes.
        /// </summary>
        internal static string get_ordenByAreaByYearByMes {
            get {
                return ResourceManager.GetString("get_ordenByAreaByYearByMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_ordenById.
        /// </summary>
        internal static string get_ordenById {
            get {
                return ResourceManager.GetString("get_ordenById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_ordenByPaciente.
        /// </summary>
        internal static string get_ordenByPaciente {
            get {
                return ResourceManager.GetString("get_ordenByPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_ordenDetalleByOrden.
        /// </summary>
        internal static string get_ordenDetalleByOrden {
            get {
                return ResourceManager.GetString("get_ordenDetalleByOrden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_ordenNoEmitidas.
        /// </summary>
        internal static string get_ordenNoEmitida {
            get {
                return ResourceManager.GetString("get_ordenNoEmitida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_ordenPendienteByPaciente.
        /// </summary>
        internal static string get_ordenPendienteByPaciente {
            get {
                return ResourceManager.GetString("get_ordenPendienteByPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_ordenTerminadas.
        /// </summary>
        internal static string get_ordenTerminadas {
            get {
                return ResourceManager.GetString("get_ordenTerminadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_pacienteByDni.
        /// </summary>
        internal static string get_pacienteByDni {
            get {
                return ResourceManager.GetString("get_pacienteByDni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_pacienteByFiltro.
        /// </summary>
        internal static string get_pacienteByFiltro {
            get {
                return ResourceManager.GetString("get_pacienteByFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_pacienteByHistoria.
        /// </summary>
        internal static string get_pacienteByHistoria {
            get {
                return ResourceManager.GetString("get_pacienteByHistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_pacienteById.
        /// </summary>
        internal static string get_pacienteById {
            get {
                return ResourceManager.GetString("get_pacienteById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_paquetes.
        /// </summary>
        internal static string get_paquetes {
            get {
                return ResourceManager.GetString("get_paquetes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_plantilla.
        /// </summary>
        internal static string get_plantilla {
            get {
                return ResourceManager.GetString("get_plantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_reporteAcumuladoMes.
        /// </summary>
        internal static string get_reporteAcumuladoMes {
            get {
                return ResourceManager.GetString("get_reporteAcumuladoMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_reporteCantidadMes.
        /// </summary>
        internal static string get_reporteCantidadMes {
            get {
                return ResourceManager.GetString("get_reporteCantidadMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_reporteEdad.
        /// </summary>
        internal static string get_reporteEdad {
            get {
                return ResourceManager.GetString("get_reporteEdad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a get_seguridad.
        /// </summary>
        internal static string get_seguridad {
            get {
                return ResourceManager.GetString("get_seguridad", resourceCulture);
            }
        }
    }
}
