//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinLab.Code.DataLayer.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProcUpd {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProcUpd() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinLab.Code.DataLayer.Recursos.ProcUpd", typeof(ProcUpd).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPD_CONSULTORIO.
        /// </summary>
        internal static string UPD_CONSULTORIO {
            get {
                return ResourceManager.GetString("UPD_CONSULTORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPD_CUENTA.
        /// </summary>
        internal static string UPD_CUENTA {
            get {
                return ResourceManager.GetString("UPD_CUENTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPD_CUENTA_CLAVE.
        /// </summary>
        internal static string UPD_CUENTA_CLAVE {
            get {
                return ResourceManager.GetString("UPD_CUENTA_CLAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPD_EXAMEN.
        /// </summary>
        internal static string UPD_EXAMEN {
            get {
                return ResourceManager.GetString("UPD_EXAMEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPD_EXAMEN_SINGLE.
        /// </summary>
        internal static string UPD_EXAMEN_SINGLE {
            get {
                return ResourceManager.GetString("UPD_EXAMEN_SINGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPD_MEDICO.
        /// </summary>
        internal static string UPD_MEDICO {
            get {
                return ResourceManager.GetString("UPD_MEDICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPD_MEDICO_HABIL.
        /// </summary>
        internal static string UPD_MEDICO_HABIL {
            get {
                return ResourceManager.GetString("UPD_MEDICO_HABIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPD_ORDENCAB.
        /// </summary>
        internal static string UPD_ORDENCAB {
            get {
                return ResourceManager.GetString("UPD_ORDENCAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPD_ORDENDET.
        /// </summary>
        internal static string UPD_ORDENDET {
            get {
                return ResourceManager.GetString("UPD_ORDENDET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPD_PACIENTE.
        /// </summary>
        internal static string UPD_PACIENTE {
            get {
                return ResourceManager.GetString("UPD_PACIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPD_SEGURIDAD.
        /// </summary>
        internal static string UPD_SEGURIDAD {
            get {
                return ResourceManager.GetString("UPD_SEGURIDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPD_TARIFARIO.
        /// </summary>
        internal static string UPD_TARIFARIO {
            get {
                return ResourceManager.GetString("UPD_TARIFARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPD_TARIFARIOCAB.
        /// </summary>
        internal static string UPD_TARIFARIOCAB {
            get {
                return ResourceManager.GetString("UPD_TARIFARIOCAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPD_TARIFARIOCAB_VIGENTE.
        /// </summary>
        internal static string UPD_TARIFARIOCAB_VIGENTE {
            get {
                return ResourceManager.GetString("UPD_TARIFARIOCAB_VIGENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPD_TARIFARIODET.
        /// </summary>
        internal static string UPD_TARIFARIODET {
            get {
                return ResourceManager.GetString("UPD_TARIFARIODET", resourceCulture);
            }
        }
    }
}
