//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinLab.Code.DataLayer.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProcUpd {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProcUpd() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinLab.Code.DataLayer.Recursos.ProcUpd", typeof(ProcUpd).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a deleted_orden.
        /// </summary>
        internal static string deleted_orden {
            get {
                return ResourceManager.GetString("deleted_orden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a deleted_ordenDetalle.
        /// </summary>
        internal static string deleted_ordenDetalle {
            get {
                return ResourceManager.GetString("deleted_ordenDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a deleted_paciente.
        /// </summary>
        internal static string deleted_paciente {
            get {
                return ResourceManager.GetString("deleted_paciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a update_examen.
        /// </summary>
        internal static string update_examen {
            get {
                return ResourceManager.GetString("update_examen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a update_examen_single.
        /// </summary>
        internal static string update_examen_single {
            get {
                return ResourceManager.GetString("update_examen_single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a update_ordenCabecera.
        /// </summary>
        internal static string update_ordenCabecera {
            get {
                return ResourceManager.GetString("update_ordenCabecera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a update_ordenDetalle.
        /// </summary>
        internal static string update_ordenDetalle {
            get {
                return ResourceManager.GetString("update_ordenDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a update_paciente.
        /// </summary>
        internal static string update_paciente {
            get {
                return ResourceManager.GetString("update_paciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a update_seguridad.
        /// </summary>
        internal static string update_seguridad {
            get {
                return ResourceManager.GetString("update_seguridad", resourceCulture);
            }
        }
    }
}
