//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinLab.Code.DataLayer.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProcAdd {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProcAdd() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinLab.Code.DataLayer.Recursos.ProcAdd", typeof(ProcAdd).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADD_CONSULTORIO.
        /// </summary>
        internal static string ADD_CONSULTORIO {
            get {
                return ResourceManager.GetString("ADD_CONSULTORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADD_CUENTA.
        /// </summary>
        internal static string ADD_CUENTA {
            get {
                return ResourceManager.GetString("ADD_CUENTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADD_DISTRITO.
        /// </summary>
        internal static string ADD_DISTRITO {
            get {
                return ResourceManager.GetString("ADD_DISTRITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADD_EXAMEN.
        /// </summary>
        internal static string ADD_EXAMEN {
            get {
                return ResourceManager.GetString("ADD_EXAMEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADD_GRUPO.
        /// </summary>
        internal static string ADD_GRUPO {
            get {
                return ResourceManager.GetString("ADD_GRUPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADD_GRUPO_ITEM.
        /// </summary>
        internal static string ADD_GRUPO_ITEM {
            get {
                return ResourceManager.GetString("ADD_GRUPO_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADD_ITEM.
        /// </summary>
        internal static string ADD_ITEM {
            get {
                return ResourceManager.GetString("ADD_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADD_LISTAITEM.
        /// </summary>
        internal static string ADD_LISTAITEM {
            get {
                return ResourceManager.GetString("ADD_LISTAITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADD_MEDICO.
        /// </summary>
        internal static string ADD_MEDICO {
            get {
                return ResourceManager.GetString("ADD_MEDICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADD_ORDENCAB.
        /// </summary>
        internal static string ADD_ORDENCAB {
            get {
                return ResourceManager.GetString("ADD_ORDENCAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADD_ORDENDET.
        /// </summary>
        internal static string ADD_ORDENDET {
            get {
                return ResourceManager.GetString("ADD_ORDENDET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADD_PACIENTE.
        /// </summary>
        internal static string ADD_PACIENTE {
            get {
                return ResourceManager.GetString("ADD_PACIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADD_PLANTILLA.
        /// </summary>
        internal static string ADD_PLANTILLA {
            get {
                return ResourceManager.GetString("ADD_PLANTILLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADD_PLANTILLA_ITEM.
        /// </summary>
        internal static string ADD_PLANTILLA_ITEM {
            get {
                return ResourceManager.GetString("ADD_PLANTILLA_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADD_SECTOR.
        /// </summary>
        internal static string ADD_SECTOR {
            get {
                return ResourceManager.GetString("ADD_SECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADD_SEGURIDAD.
        /// </summary>
        internal static string ADD_SEGURIDAD {
            get {
                return ResourceManager.GetString("ADD_SEGURIDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADD_TARIFARIOCAB.
        /// </summary>
        internal static string ADD_TARIFARIOCAB {
            get {
                return ResourceManager.GetString("ADD_TARIFARIOCAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADD_TARIFARIODET.
        /// </summary>
        internal static string ADD_TARIFARIODET {
            get {
                return ResourceManager.GetString("ADD_TARIFARIODET", resourceCulture);
            }
        }
    }
}
