//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinLab.Code.DataLayer.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProcGet {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProcGet() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinLab.Code.DataLayer.Recursos.ProcGet", typeof(ProcGet).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_CONSULTORIO_ALL.
        /// </summary>
        internal static string GET_CONSULTORIO_ALL {
            get {
                return ResourceManager.GetString("GET_CONSULTORIO_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_CUENTA.
        /// </summary>
        internal static string GET_CUENTA {
            get {
                return ResourceManager.GetString("GET_CUENTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_CUENTA_BYID.
        /// </summary>
        internal static string GET_CUENTA_BYID {
            get {
                return ResourceManager.GetString("GET_CUENTA_BYID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_CUENTA_EXISTE.
        /// </summary>
        internal static string GET_CUENTA_EXISTE {
            get {
                return ResourceManager.GetString("GET_CUENTA_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_DISTRITO_ALL.
        /// </summary>
        internal static string GET_DISTRITO_ALL {
            get {
                return ResourceManager.GetString("GET_DISTRITO_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_EXAMENCAB_BYORDENDET.
        /// </summary>
        internal static string GET_EXAMENCAB_BYORDENDET {
            get {
                return ResourceManager.GetString("GET_EXAMENCAB_BYORDENDET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_EXAMENCAB_EXISTE.
        /// </summary>
        internal static string GET_EXAMENCAB_EXISTE {
            get {
                return ResourceManager.GetString("GET_EXAMENCAB_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_EXAMENDET_BYEXAMENCAB.
        /// </summary>
        internal static string GET_EXAMENDET_BYEXAMENCAB {
            get {
                return ResourceManager.GetString("GET_EXAMENDET_BYEXAMENCAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_GRUPO_BYPLANTILLA.
        /// </summary>
        internal static string GET_GRUPO_BYPLANTILLA {
            get {
                return ResourceManager.GetString("GET_GRUPO_BYPLANTILLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_ITEM_ALL_BYPLANTILLA.
        /// </summary>
        internal static string GET_ITEM_ALL_BYPLANTILLA {
            get {
                return ResourceManager.GetString("GET_ITEM_ALL_BYPLANTILLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_ITEM_BYGRUPO.
        /// </summary>
        internal static string GET_ITEM_BYGRUPO {
            get {
                return ResourceManager.GetString("GET_ITEM_BYGRUPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_ITEM_BYPLANTILLA.
        /// </summary>
        internal static string GET_ITEM_BYPLANTILLA {
            get {
                return ResourceManager.GetString("GET_ITEM_BYPLANTILLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_LISTA_BYITEM.
        /// </summary>
        internal static string GET_LISTA_BYITEM {
            get {
                return ResourceManager.GetString("GET_LISTA_BYITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_MEDICO.
        /// </summary>
        internal static string GET_MEDICO {
            get {
                return ResourceManager.GetString("GET_MEDICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_MEDICO_ALL.
        /// </summary>
        internal static string GET_MEDICO_ALL {
            get {
                return ResourceManager.GetString("GET_MEDICO_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_MEDICO_ALL_HABIL.
        /// </summary>
        internal static string GET_MEDICO_ALL_HABIL {
            get {
                return ResourceManager.GetString("GET_MEDICO_ALL_HABIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_MEDICO_BYFILTRO.
        /// </summary>
        internal static string GET_MEDICO_BYFILTRO {
            get {
                return ResourceManager.GetString("GET_MEDICO_BYFILTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_ORDENCAB_ALL_BYFECHA.
        /// </summary>
        internal static string GET_ORDENCAB_ALL_BYFECHA {
            get {
                return ResourceManager.GetString("GET_ORDENCAB_ALL_BYFECHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_ORDENCAB_ALL_BYFECHA_BYESTADO.
        /// </summary>
        internal static string GET_ORDENCAB_ALL_BYFECHA_BYESTADO {
            get {
                return ResourceManager.GetString("GET_ORDENCAB_ALL_BYFECHA_BYESTADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_ORDENCAB_ALL_BYPACIENTE_BYFECHA_BYESTADO.
        /// </summary>
        internal static string GET_ORDENCAB_ALL_BYPACIENTE_BYFECHA_BYESTADO {
            get {
                return ResourceManager.GetString("GET_ORDENCAB_ALL_BYPACIENTE_BYFECHA_BYESTADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_ORDENCAB_ALL_NOEMITIDA.
        /// </summary>
        internal static string GET_ORDENCAB_ALL_NOEMITIDA {
            get {
                return ResourceManager.GetString("GET_ORDENCAB_ALL_NOEMITIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_ORDENCAB_BYAREA_BYYEAR_BYMES.
        /// </summary>
        internal static string GET_ORDENCAB_BYAREA_BYYEAR_BYMES {
            get {
                return ResourceManager.GetString("GET_ORDENCAB_BYAREA_BYYEAR_BYMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_ORDENCAB_BYID.
        /// </summary>
        internal static string GET_ORDENCAB_BYID {
            get {
                return ResourceManager.GetString("GET_ORDENCAB_BYID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_ORDENCAB_BYPACIENTE.
        /// </summary>
        internal static string GET_ORDENCAB_BYPACIENTE {
            get {
                return ResourceManager.GetString("GET_ORDENCAB_BYPACIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_ORDENCAB_PENDIENTES_BYPACIENTE.
        /// </summary>
        internal static string GET_ORDENCAB_PENDIENTES_BYPACIENTE {
            get {
                return ResourceManager.GetString("GET_ORDENCAB_PENDIENTES_BYPACIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_ORDENCAB_TERMINADA.
        /// </summary>
        internal static string GET_ORDENCAB_TERMINADA {
            get {
                return ResourceManager.GetString("GET_ORDENCAB_TERMINADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_ORDENDET_BYORDENCAB.
        /// </summary>
        internal static string GET_ORDENDET_BYORDENCAB {
            get {
                return ResourceManager.GetString("GET_ORDENDET_BYORDENCAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_PACIENTE_BYDNI.
        /// </summary>
        internal static string GET_PACIENTE_BYDNI {
            get {
                return ResourceManager.GetString("GET_PACIENTE_BYDNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_PACIENTE_BYHISTORIA.
        /// </summary>
        internal static string GET_PACIENTE_BYHISTORIA {
            get {
                return ResourceManager.GetString("GET_PACIENTE_BYHISTORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_PACIENTE_BYID.
        /// </summary>
        internal static string GET_PACIENTE_BYID {
            get {
                return ResourceManager.GetString("GET_PACIENTE_BYID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_PAQUETE_ALL.
        /// </summary>
        internal static string GET_PAQUETE_ALL {
            get {
                return ResourceManager.GetString("GET_PAQUETE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_PLANTILLA.
        /// </summary>
        internal static string GET_PLANTILLA {
            get {
                return ResourceManager.GetString("GET_PLANTILLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_PLANTILLA_ALL.
        /// </summary>
        internal static string GET_PLANTILLA_ALL {
            get {
                return ResourceManager.GetString("GET_PLANTILLA_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_PLANTILLA_COD_BYPAQUETE.
        /// </summary>
        internal static string GET_PLANTILLA_COD_BYPAQUETE {
            get {
                return ResourceManager.GetString("GET_PLANTILLA_COD_BYPAQUETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_REPORTE_ACUMULADOMES.
        /// </summary>
        internal static string GET_REPORTE_ACUMULADOMES {
            get {
                return ResourceManager.GetString("GET_REPORTE_ACUMULADOMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_REPORTE_CANTIDADMES.
        /// </summary>
        internal static string GET_REPORTE_CANTIDADMES {
            get {
                return ResourceManager.GetString("GET_REPORTE_CANTIDADMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_REPORTE_EDAD.
        /// </summary>
        internal static string GET_REPORTE_EDAD {
            get {
                return ResourceManager.GetString("GET_REPORTE_EDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_REPORTE_MEDICO_ACUMULADOMES.
        /// </summary>
        internal static string GET_REPORTE_MEDICO_ACUMULADOMES {
            get {
                return ResourceManager.GetString("GET_REPORTE_MEDICO_ACUMULADOMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_REPORTE_MEDICO_CANTIDADMES.
        /// </summary>
        internal static string GET_REPORTE_MEDICO_CANTIDADMES {
            get {
                return ResourceManager.GetString("GET_REPORTE_MEDICO_CANTIDADMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_REPORTE_RESULTADO.
        /// </summary>
        internal static string GET_REPORTE_RESULTADO {
            get {
                return ResourceManager.GetString("GET_REPORTE_RESULTADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_SECTOR_BYDISTRITO.
        /// </summary>
        internal static string GET_SECTOR_BYDISTRITO {
            get {
                return ResourceManager.GetString("GET_SECTOR_BYDISTRITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_SEGURIDAD.
        /// </summary>
        internal static string GET_SEGURIDAD {
            get {
                return ResourceManager.GetString("GET_SEGURIDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_TARIFARIOCAB_ALL.
        /// </summary>
        internal static string GET_TARIFARIOCAB_ALL {
            get {
                return ResourceManager.GetString("GET_TARIFARIOCAB_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_TARIFARIOCAB_BYANO.
        /// </summary>
        internal static string GET_TARIFARIOCAB_BYANO {
            get {
                return ResourceManager.GetString("GET_TARIFARIOCAB_BYANO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_TARIFARIOCAB_BYID.
        /// </summary>
        internal static string GET_TARIFARIOCAB_BYID {
            get {
                return ResourceManager.GetString("GET_TARIFARIOCAB_BYID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_TARIFARIOCAB_CHECK_BYYEAR.
        /// </summary>
        internal static string GET_TARIFARIOCAB_CHECK_BYYEAR {
            get {
                return ResourceManager.GetString("GET_TARIFARIOCAB_CHECK_BYYEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_TARIFARIOCAB_HABIL.
        /// </summary>
        internal static string GET_TARIFARIOCAB_HABIL {
            get {
                return ResourceManager.GetString("GET_TARIFARIOCAB_HABIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET_TARIFARIODET_BYTARIFARIOCAB.
        /// </summary>
        internal static string GET_TARIFARIODET_BYTARIFARIOCAB {
            get {
                return ResourceManager.GetString("GET_TARIFARIODET_BYTARIFARIOCAB", resourceCulture);
            }
        }
    }
}
